@prefix schema: <http://schema.org/>

CONSTRUCT {
    ?recipe a schema:Recipe .
    ?recipe schema:recipeIngredient ?food .
    ?recipe schema:name ?recipeName ;

} WHERE {
    [] api:recipe ?recipe .
    ?recipe api:label ?recipeName .
    ?recipe api:ingredients [ api:food ?food ] .
}