@prefix : <http://recipes-project.com/schema#> .
@prefix s: <https://schema.org#> .
@prefix recipes: <http://recipes-project.com/recipes#> .

CONSTRUCT {
    ?recipe a :Recipe .
    ?recipe :name ?recipeName .
    ?recipe :recipeIngredient ?food .
    ?dishType a :RecipeCategory .
    ?recipe :recipeCategory ?dishType .
    ?recipe :healthLabels ?healthLabels .
    ?recipe :calories ?calories .

} WHERE {
    [] api:recipe ?recipe .
    ?recipe api:label ?recipeName .
    ?recipe api:ingredients [ api:food ?food ] .
    ?recipe api:dishType ?dishType .
    ?recipe api:healthLabels ?healthLabels .
    ?recipe api:calories ?calories .
}